---
title: "Thermal tolerance landscapes across populations and communities: applications in a changing world"
bibliography: ../bib/refs.bib
csl: ../bib/trends-in-ecology-and-evolution.csl
format:
  docx:
    reference-doc: ../bib/template.docx
  pdf:
    include-in-header: 
      text: '\usepackage{lineno}\linenumbers'
editor_options: 
  chunk_output_type: console
execute:
  freeze: auto  # re-render only when source changes
  cache: false
  echo: false
  warning: false
  error: false
  include: true
crossref:
  fig-title: 'Figure'
  fig-labels: arabic
  title-delim: "-"
  fig-prefix: "Figure"
  tbl-prefix: "Table"
---
# Introduction

Márquez *et. al* @marquez2007virus describe a three-way mutulastic assocation between a tropical panic grass (*Dichanthelium lanuginosum*), the fungus, *Curvularia protuberata*, and a *Curvularia* thermal tolerance virus whereby thermal tolerance of the fungus and grass is highly dependent on fungal-virus associations. Endophytic fungus cured of the virus were unable to survive extreme heating events (temperatures of 65$^\circ$C for 2 weeks). However, when the fungus were inoculated with the virus, heat tolerance was restored. Fascinatingly, the virus could be manipulated to confer heat tolerance to tomato (*Solanum lycopersicon*) demonstrating the potential for conferring thermal tolerance to other plant species. The mechanisms by which fungal-virus associations confer thermal tolerance are not yet understood but are hypothesized to involve scavenging of reactive oxygen species (ROS) by fungal endophytes generated by plant defense mechanisms in response to heat stress. 

Li *et al* @li2023interspecific measured the thermal tolerance landscape for three aphid species that are pests for cereal crops globally to understand whether it could predict changes in community abundance. Using a thermal death time (TDT) approach to estimate the culmuative impacts of heat stress on survival they found that one species, *Rhopalosiphum padi*, showed high heat tolerance and accumulated less injury over natural temperature fluctuations, which may explain the increase in relative abundance of this species with extremely high temperatures observed in southern parts of its range. Li *et al* @li2023interspecific also found that different life-stages were affected differently by heat stress, with adults being more thermally tolerant than early developmental stages emphasising the need for models to capture such variation. However, such findings do not incorperate acclimation to heat stress or different microhabitat choice by the different species, which are both likely to be important for predicting the impacts of heat stress on community structure.

# Methods for manipulating thermal tolerance

*Genetic engineering*: The use of genetic engineering to confer thermal tolerance to plants and animals is a promising avenue for enhancing thermal tolerance. For example, the overexpression of heat shock proteins (HSPs) in plants has been shown to enhance thermal tolerance. HSPs are a family of proteins that are upregulated in response to heat stress and are involved in protein folding and degradation, and the prevention of protein aggregation. CRISPR-Cas9 gene editing technology has been used to enhance thermal tolerance in plants by modifying genes involved in heat stress response.

*Selective breeding*: Artifical selection will be a useful avenue for both plants and animals to enhance thermal tolerance. 

# Opportunities for modelling thermal tolerance landscapes to capture interactions*

-chat with Mike about this some more.

## Differenecs in focus for plants and animals
- Animals behave. We need to model that. HOw do changes in behaviour impact inetractions with other species and the environment. How might this impact plant productivity   

# Future Directions

*Better understanding of the mechanisms enhancing thermal tolerance in plants and animals*: We need to understand the genomic, cellular and physiological processes that confer greater thermal tolerance and help prepare organisms for future heat stress events.

*Modelling inetractions among plants and animals to build community thermal tolerance landscapes and predict how heat stress events will affect communities*: We need to understand how thermal tolerance of individual species will affect the thermal tolerance of communities and ecosystems.

*Trade-offs between thermal tolerance and other traits*: We need to understand the trade-offs between thermal tolerance and other traits such as growth rate, reproduction, and competitive ability. It is fine to confer greater thermal tolerance resistance but if this comes at a cost to reproduction, growth or biomass accumulation, then it may not be beneficial. NEED EXAPLES

# References